name: Deploy Code to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Package code
        run: |
          # Replace 'my-function' with your actual function name or directory containing code
          zip -r deployment-package.zip my-function/
        # Optional: You can add more files and directories to the ZIP if needed, using the 'zip' command.

      - name: Upload the packaged code
        uses: actions/upload-artifact@v2
        with:
          name: deployment-package
          path: deployment-package.zip

      - name: Deploy to AWS Lambda
        run: |
          # Install AWS CLI
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

          # Replace with your AWS Lambda function name and AWS region
          aws lambda update-function-code \
            --function-name YourLambdaFunctionName \
            --zip-file fileb://./deployment-package.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

